package com.dandelion.membership.dao.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ApplicantExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tb_applicant
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tb_applicant
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tb_applicant
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_applicant
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public ApplicantExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_applicant
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_applicant
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_applicant
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_applicant
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_applicant
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_applicant
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_applicant
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_applicant
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_applicant
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_applicant
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tb_applicant
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()),
					property);
		}

		protected void addCriterionForJDBCDate(String condition,
				List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1,
				Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()),
					new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andApplicantnameIsNull() {
			addCriterion("applicantName is null");
			return (Criteria) this;
		}

		public Criteria andApplicantnameIsNotNull() {
			addCriterion("applicantName is not null");
			return (Criteria) this;
		}

		public Criteria andApplicantnameEqualTo(String value) {
			addCriterion("applicantName =", value, "applicantname");
			return (Criteria) this;
		}

		public Criteria andApplicantnameNotEqualTo(String value) {
			addCriterion("applicantName <>", value, "applicantname");
			return (Criteria) this;
		}

		public Criteria andApplicantnameGreaterThan(String value) {
			addCriterion("applicantName >", value, "applicantname");
			return (Criteria) this;
		}

		public Criteria andApplicantnameGreaterThanOrEqualTo(String value) {
			addCriterion("applicantName >=", value, "applicantname");
			return (Criteria) this;
		}

		public Criteria andApplicantnameLessThan(String value) {
			addCriterion("applicantName <", value, "applicantname");
			return (Criteria) this;
		}

		public Criteria andApplicantnameLessThanOrEqualTo(String value) {
			addCriterion("applicantName <=", value, "applicantname");
			return (Criteria) this;
		}

		public Criteria andApplicantnameLike(String value) {
			addCriterion("applicantName like", value, "applicantname");
			return (Criteria) this;
		}

		public Criteria andApplicantnameNotLike(String value) {
			addCriterion("applicantName not like", value, "applicantname");
			return (Criteria) this;
		}

		public Criteria andApplicantnameIn(List<String> values) {
			addCriterion("applicantName in", values, "applicantname");
			return (Criteria) this;
		}

		public Criteria andApplicantnameNotIn(List<String> values) {
			addCriterion("applicantName not in", values, "applicantname");
			return (Criteria) this;
		}

		public Criteria andApplicantnameBetween(String value1, String value2) {
			addCriterion("applicantName between", value1, value2,
					"applicantname");
			return (Criteria) this;
		}

		public Criteria andApplicantnameNotBetween(String value1, String value2) {
			addCriterion("applicantName not between", value1, value2,
					"applicantname");
			return (Criteria) this;
		}

		public Criteria andApplydateIsNull() {
			addCriterion("applyDate is null");
			return (Criteria) this;
		}

		public Criteria andApplydateIsNotNull() {
			addCriterion("applyDate is not null");
			return (Criteria) this;
		}

		public Criteria andApplydateEqualTo(Date value) {
			addCriterionForJDBCDate("applyDate =", value, "applydate");
			return (Criteria) this;
		}

		public Criteria andApplydateNotEqualTo(Date value) {
			addCriterionForJDBCDate("applyDate <>", value, "applydate");
			return (Criteria) this;
		}

		public Criteria andApplydateGreaterThan(Date value) {
			addCriterionForJDBCDate("applyDate >", value, "applydate");
			return (Criteria) this;
		}

		public Criteria andApplydateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("applyDate >=", value, "applydate");
			return (Criteria) this;
		}

		public Criteria andApplydateLessThan(Date value) {
			addCriterionForJDBCDate("applyDate <", value, "applydate");
			return (Criteria) this;
		}

		public Criteria andApplydateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("applyDate <=", value, "applydate");
			return (Criteria) this;
		}

		public Criteria andApplydateIn(List<Date> values) {
			addCriterionForJDBCDate("applyDate in", values, "applydate");
			return (Criteria) this;
		}

		public Criteria andApplydateNotIn(List<Date> values) {
			addCriterionForJDBCDate("applyDate not in", values, "applydate");
			return (Criteria) this;
		}

		public Criteria andApplydateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("applyDate between", value1, value2,
					"applydate");
			return (Criteria) this;
		}

		public Criteria andApplydateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("applyDate not between", value1, value2,
					"applydate");
			return (Criteria) this;
		}

		public Criteria andReferrernameIsNull() {
			addCriterion("referrerName is null");
			return (Criteria) this;
		}

		public Criteria andReferrernameIsNotNull() {
			addCriterion("referrerName is not null");
			return (Criteria) this;
		}

		public Criteria andReferrernameEqualTo(String value) {
			addCriterion("referrerName =", value, "referrername");
			return (Criteria) this;
		}

		public Criteria andReferrernameNotEqualTo(String value) {
			addCriterion("referrerName <>", value, "referrername");
			return (Criteria) this;
		}

		public Criteria andReferrernameGreaterThan(String value) {
			addCriterion("referrerName >", value, "referrername");
			return (Criteria) this;
		}

		public Criteria andReferrernameGreaterThanOrEqualTo(String value) {
			addCriterion("referrerName >=", value, "referrername");
			return (Criteria) this;
		}

		public Criteria andReferrernameLessThan(String value) {
			addCriterion("referrerName <", value, "referrername");
			return (Criteria) this;
		}

		public Criteria andReferrernameLessThanOrEqualTo(String value) {
			addCriterion("referrerName <=", value, "referrername");
			return (Criteria) this;
		}

		public Criteria andReferrernameLike(String value) {
			addCriterion("referrerName like", value, "referrername");
			return (Criteria) this;
		}

		public Criteria andReferrernameNotLike(String value) {
			addCriterion("referrerName not like", value, "referrername");
			return (Criteria) this;
		}

		public Criteria andReferrernameIn(List<String> values) {
			addCriterion("referrerName in", values, "referrername");
			return (Criteria) this;
		}

		public Criteria andReferrernameNotIn(List<String> values) {
			addCriterion("referrerName not in", values, "referrername");
			return (Criteria) this;
		}

		public Criteria andReferrernameBetween(String value1, String value2) {
			addCriterion("referrerName between", value1, value2, "referrername");
			return (Criteria) this;
		}

		public Criteria andReferrernameNotBetween(String value1, String value2) {
			addCriterion("referrerName not between", value1, value2,
					"referrername");
			return (Criteria) this;
		}

		public Criteria andCreditcardnumberIsNull() {
			addCriterion("creditCardNumber is null");
			return (Criteria) this;
		}

		public Criteria andCreditcardnumberIsNotNull() {
			addCriterion("creditCardNumber is not null");
			return (Criteria) this;
		}

		public Criteria andCreditcardnumberEqualTo(String value) {
			addCriterion("creditCardNumber =", value, "creditcardnumber");
			return (Criteria) this;
		}

		public Criteria andCreditcardnumberNotEqualTo(String value) {
			addCriterion("creditCardNumber <>", value, "creditcardnumber");
			return (Criteria) this;
		}

		public Criteria andCreditcardnumberGreaterThan(String value) {
			addCriterion("creditCardNumber >", value, "creditcardnumber");
			return (Criteria) this;
		}

		public Criteria andCreditcardnumberGreaterThanOrEqualTo(String value) {
			addCriterion("creditCardNumber >=", value, "creditcardnumber");
			return (Criteria) this;
		}

		public Criteria andCreditcardnumberLessThan(String value) {
			addCriterion("creditCardNumber <", value, "creditcardnumber");
			return (Criteria) this;
		}

		public Criteria andCreditcardnumberLessThanOrEqualTo(String value) {
			addCriterion("creditCardNumber <=", value, "creditcardnumber");
			return (Criteria) this;
		}

		public Criteria andCreditcardnumberLike(String value) {
			addCriterion("creditCardNumber like", value, "creditcardnumber");
			return (Criteria) this;
		}

		public Criteria andCreditcardnumberNotLike(String value) {
			addCriterion("creditCardNumber not like", value, "creditcardnumber");
			return (Criteria) this;
		}

		public Criteria andCreditcardnumberIn(List<String> values) {
			addCriterion("creditCardNumber in", values, "creditcardnumber");
			return (Criteria) this;
		}

		public Criteria andCreditcardnumberNotIn(List<String> values) {
			addCriterion("creditCardNumber not in", values, "creditcardnumber");
			return (Criteria) this;
		}

		public Criteria andCreditcardnumberBetween(String value1, String value2) {
			addCriterion("creditCardNumber between", value1, value2,
					"creditcardnumber");
			return (Criteria) this;
		}

		public Criteria andCreditcardnumberNotBetween(String value1,
				String value2) {
			addCriterion("creditCardNumber not between", value1, value2,
					"creditcardnumber");
			return (Criteria) this;
		}

		public Criteria andMembertypeIsNull() {
			addCriterion("memberType is null");
			return (Criteria) this;
		}

		public Criteria andMembertypeIsNotNull() {
			addCriterion("memberType is not null");
			return (Criteria) this;
		}

		public Criteria andMembertypeEqualTo(String value) {
			addCriterion("memberType =", value, "membertype");
			return (Criteria) this;
		}

		public Criteria andMembertypeNotEqualTo(String value) {
			addCriterion("memberType <>", value, "membertype");
			return (Criteria) this;
		}

		public Criteria andMembertypeGreaterThan(String value) {
			addCriterion("memberType >", value, "membertype");
			return (Criteria) this;
		}

		public Criteria andMembertypeGreaterThanOrEqualTo(String value) {
			addCriterion("memberType >=", value, "membertype");
			return (Criteria) this;
		}

		public Criteria andMembertypeLessThan(String value) {
			addCriterion("memberType <", value, "membertype");
			return (Criteria) this;
		}

		public Criteria andMembertypeLessThanOrEqualTo(String value) {
			addCriterion("memberType <=", value, "membertype");
			return (Criteria) this;
		}

		public Criteria andMembertypeLike(String value) {
			addCriterion("memberType like", value, "membertype");
			return (Criteria) this;
		}

		public Criteria andMembertypeNotLike(String value) {
			addCriterion("memberType not like", value, "membertype");
			return (Criteria) this;
		}

		public Criteria andMembertypeIn(List<String> values) {
			addCriterion("memberType in", values, "membertype");
			return (Criteria) this;
		}

		public Criteria andMembertypeNotIn(List<String> values) {
			addCriterion("memberType not in", values, "membertype");
			return (Criteria) this;
		}

		public Criteria andMembertypeBetween(String value1, String value2) {
			addCriterion("memberType between", value1, value2, "membertype");
			return (Criteria) this;
		}

		public Criteria andMembertypeNotBetween(String value1, String value2) {
			addCriterion("memberType not between", value1, value2, "membertype");
			return (Criteria) this;
		}

		public Criteria andCreateddateIsNull() {
			addCriterion("CreatedDate is null");
			return (Criteria) this;
		}

		public Criteria andCreateddateIsNotNull() {
			addCriterion("CreatedDate is not null");
			return (Criteria) this;
		}

		public Criteria andCreateddateEqualTo(Date value) {
			addCriterion("CreatedDate =", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateNotEqualTo(Date value) {
			addCriterion("CreatedDate <>", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateGreaterThan(Date value) {
			addCriterion("CreatedDate >", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateGreaterThanOrEqualTo(Date value) {
			addCriterion("CreatedDate >=", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateLessThan(Date value) {
			addCriterion("CreatedDate <", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateLessThanOrEqualTo(Date value) {
			addCriterion("CreatedDate <=", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateIn(List<Date> values) {
			addCriterion("CreatedDate in", values, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateNotIn(List<Date> values) {
			addCriterion("CreatedDate not in", values, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateBetween(Date value1, Date value2) {
			addCriterion("CreatedDate between", value1, value2, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateNotBetween(Date value1, Date value2) {
			addCriterion("CreatedDate not between", value1, value2,
					"createddate");
			return (Criteria) this;
		}

		public Criteria andModifieddateIsNull() {
			addCriterion("ModifiedDate is null");
			return (Criteria) this;
		}

		public Criteria andModifieddateIsNotNull() {
			addCriterion("ModifiedDate is not null");
			return (Criteria) this;
		}

		public Criteria andModifieddateEqualTo(Date value) {
			addCriterion("ModifiedDate =", value, "modifieddate");
			return (Criteria) this;
		}

		public Criteria andModifieddateNotEqualTo(Date value) {
			addCriterion("ModifiedDate <>", value, "modifieddate");
			return (Criteria) this;
		}

		public Criteria andModifieddateGreaterThan(Date value) {
			addCriterion("ModifiedDate >", value, "modifieddate");
			return (Criteria) this;
		}

		public Criteria andModifieddateGreaterThanOrEqualTo(Date value) {
			addCriterion("ModifiedDate >=", value, "modifieddate");
			return (Criteria) this;
		}

		public Criteria andModifieddateLessThan(Date value) {
			addCriterion("ModifiedDate <", value, "modifieddate");
			return (Criteria) this;
		}

		public Criteria andModifieddateLessThanOrEqualTo(Date value) {
			addCriterion("ModifiedDate <=", value, "modifieddate");
			return (Criteria) this;
		}

		public Criteria andModifieddateIn(List<Date> values) {
			addCriterion("ModifiedDate in", values, "modifieddate");
			return (Criteria) this;
		}

		public Criteria andModifieddateNotIn(List<Date> values) {
			addCriterion("ModifiedDate not in", values, "modifieddate");
			return (Criteria) this;
		}

		public Criteria andModifieddateBetween(Date value1, Date value2) {
			addCriterion("ModifiedDate between", value1, value2, "modifieddate");
			return (Criteria) this;
		}

		public Criteria andModifieddateNotBetween(Date value1, Date value2) {
			addCriterion("ModifiedDate not between", value1, value2,
					"modifieddate");
			return (Criteria) this;
		}

		public Criteria andIsdeletedIsNull() {
			addCriterion("IsDeleted is null");
			return (Criteria) this;
		}

		public Criteria andIsdeletedIsNotNull() {
			addCriterion("IsDeleted is not null");
			return (Criteria) this;
		}

		public Criteria andIsdeletedEqualTo(Boolean value) {
			addCriterion("IsDeleted =", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedNotEqualTo(Boolean value) {
			addCriterion("IsDeleted <>", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedGreaterThan(Boolean value) {
			addCriterion("IsDeleted >", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedGreaterThanOrEqualTo(Boolean value) {
			addCriterion("IsDeleted >=", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedLessThan(Boolean value) {
			addCriterion("IsDeleted <", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedLessThanOrEqualTo(Boolean value) {
			addCriterion("IsDeleted <=", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedIn(List<Boolean> values) {
			addCriterion("IsDeleted in", values, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedNotIn(List<Boolean> values) {
			addCriterion("IsDeleted not in", values, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedBetween(Boolean value1, Boolean value2) {
			addCriterion("IsDeleted between", value1, value2, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedNotBetween(Boolean value1, Boolean value2) {
			addCriterion("IsDeleted not between", value1, value2, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("status like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("status not like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<String> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<String> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(String value1, String value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andIsmemberIsNull() {
			addCriterion("IsMember is null");
			return (Criteria) this;
		}

		public Criteria andIsmemberIsNotNull() {
			addCriterion("IsMember is not null");
			return (Criteria) this;
		}

		public Criteria andIsmemberEqualTo(Boolean value) {
			addCriterion("IsMember =", value, "ismember");
			return (Criteria) this;
		}

		public Criteria andIsmemberNotEqualTo(Boolean value) {
			addCriterion("IsMember <>", value, "ismember");
			return (Criteria) this;
		}

		public Criteria andIsmemberGreaterThan(Boolean value) {
			addCriterion("IsMember >", value, "ismember");
			return (Criteria) this;
		}

		public Criteria andIsmemberGreaterThanOrEqualTo(Boolean value) {
			addCriterion("IsMember >=", value, "ismember");
			return (Criteria) this;
		}

		public Criteria andIsmemberLessThan(Boolean value) {
			addCriterion("IsMember <", value, "ismember");
			return (Criteria) this;
		}

		public Criteria andIsmemberLessThanOrEqualTo(Boolean value) {
			addCriterion("IsMember <=", value, "ismember");
			return (Criteria) this;
		}

		public Criteria andIsmemberIn(List<Boolean> values) {
			addCriterion("IsMember in", values, "ismember");
			return (Criteria) this;
		}

		public Criteria andIsmemberNotIn(List<Boolean> values) {
			addCriterion("IsMember not in", values, "ismember");
			return (Criteria) this;
		}

		public Criteria andIsmemberBetween(Boolean value1, Boolean value2) {
			addCriterion("IsMember between", value1, value2, "ismember");
			return (Criteria) this;
		}

		public Criteria andIsmemberNotBetween(Boolean value1, Boolean value2) {
			addCriterion("IsMember not between", value1, value2, "ismember");
			return (Criteria) this;
		}

		public Criteria andIsreferrertrueIsNull() {
			addCriterion("IsReferrerTrue is null");
			return (Criteria) this;
		}

		public Criteria andIsreferrertrueIsNotNull() {
			addCriterion("IsReferrerTrue is not null");
			return (Criteria) this;
		}

		public Criteria andIsreferrertrueEqualTo(Boolean value) {
			addCriterion("IsReferrerTrue =", value, "isreferrertrue");
			return (Criteria) this;
		}

		public Criteria andIsreferrertrueNotEqualTo(Boolean value) {
			addCriterion("IsReferrerTrue <>", value, "isreferrertrue");
			return (Criteria) this;
		}

		public Criteria andIsreferrertrueGreaterThan(Boolean value) {
			addCriterion("IsReferrerTrue >", value, "isreferrertrue");
			return (Criteria) this;
		}

		public Criteria andIsreferrertrueGreaterThanOrEqualTo(Boolean value) {
			addCriterion("IsReferrerTrue >=", value, "isreferrertrue");
			return (Criteria) this;
		}

		public Criteria andIsreferrertrueLessThan(Boolean value) {
			addCriterion("IsReferrerTrue <", value, "isreferrertrue");
			return (Criteria) this;
		}

		public Criteria andIsreferrertrueLessThanOrEqualTo(Boolean value) {
			addCriterion("IsReferrerTrue <=", value, "isreferrertrue");
			return (Criteria) this;
		}

		public Criteria andIsreferrertrueIn(List<Boolean> values) {
			addCriterion("IsReferrerTrue in", values, "isreferrertrue");
			return (Criteria) this;
		}

		public Criteria andIsreferrertrueNotIn(List<Boolean> values) {
			addCriterion("IsReferrerTrue not in", values, "isreferrertrue");
			return (Criteria) this;
		}

		public Criteria andIsreferrertrueBetween(Boolean value1, Boolean value2) {
			addCriterion("IsReferrerTrue between", value1, value2,
					"isreferrertrue");
			return (Criteria) this;
		}

		public Criteria andIsreferrertrueNotBetween(Boolean value1,
				Boolean value2) {
			addCriterion("IsReferrerTrue not between", value1, value2,
					"isreferrertrue");
			return (Criteria) this;
		}

		public Criteria andApplicantemailIsNull() {
			addCriterion("applicantEmail is null");
			return (Criteria) this;
		}

		public Criteria andApplicantemailIsNotNull() {
			addCriterion("applicantEmail is not null");
			return (Criteria) this;
		}

		public Criteria andApplicantemailEqualTo(String value) {
			addCriterion("applicantEmail =", value, "applicantemail");
			return (Criteria) this;
		}

		public Criteria andApplicantemailNotEqualTo(String value) {
			addCriterion("applicantEmail <>", value, "applicantemail");
			return (Criteria) this;
		}

		public Criteria andApplicantemailGreaterThan(String value) {
			addCriterion("applicantEmail >", value, "applicantemail");
			return (Criteria) this;
		}

		public Criteria andApplicantemailGreaterThanOrEqualTo(String value) {
			addCriterion("applicantEmail >=", value, "applicantemail");
			return (Criteria) this;
		}

		public Criteria andApplicantemailLessThan(String value) {
			addCriterion("applicantEmail <", value, "applicantemail");
			return (Criteria) this;
		}

		public Criteria andApplicantemailLessThanOrEqualTo(String value) {
			addCriterion("applicantEmail <=", value, "applicantemail");
			return (Criteria) this;
		}

		public Criteria andApplicantemailLike(String value) {
			addCriterion("applicantEmail like", value, "applicantemail");
			return (Criteria) this;
		}

		public Criteria andApplicantemailNotLike(String value) {
			addCriterion("applicantEmail not like", value, "applicantemail");
			return (Criteria) this;
		}

		public Criteria andApplicantemailIn(List<String> values) {
			addCriterion("applicantEmail in", values, "applicantemail");
			return (Criteria) this;
		}

		public Criteria andApplicantemailNotIn(List<String> values) {
			addCriterion("applicantEmail not in", values, "applicantemail");
			return (Criteria) this;
		}

		public Criteria andApplicantemailBetween(String value1, String value2) {
			addCriterion("applicantEmail between", value1, value2,
					"applicantemail");
			return (Criteria) this;
		}

		public Criteria andApplicantemailNotBetween(String value1, String value2) {
			addCriterion("applicantEmail not between", value1, value2,
					"applicantemail");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tb_applicant
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_applicant
     *
     * @mbggenerated do_not_delete_during_merge Fri Nov 08 21:20:31 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}