package com.dandelion.membership.dao.model;

import java.util.Date;

public class Applicant {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_applicant.ID
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_applicant.applicantName
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	private String applicantname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_applicant.applyDate
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	private Date applydate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_applicant.referrerName
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	private String referrername;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_applicant.creditCardNumber
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	private String creditcardnumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_applicant.memberType
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	private String membertype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_applicant.CreatedDate
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	private Date createddate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_applicant.ModifiedDate
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	private Date modifieddate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_applicant.IsDeleted
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	private Boolean isdeleted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_applicant.status
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_applicant.IsMember
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	private Boolean ismember;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_applicant.IsReferrerTrue
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	private Boolean isreferrertrue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_applicant.applicantEmail
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	private String applicantemail;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_applicant.ID
	 * @return  the value of tb_applicant.ID
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_applicant.ID
	 * @param id  the value for tb_applicant.ID
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_applicant.applicantName
	 * @return  the value of tb_applicant.applicantName
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public String getApplicantname() {
		return applicantname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_applicant.applicantName
	 * @param applicantname  the value for tb_applicant.applicantName
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public void setApplicantname(String applicantname) {
		this.applicantname = applicantname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_applicant.applyDate
	 * @return  the value of tb_applicant.applyDate
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public Date getApplydate() {
		return applydate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_applicant.applyDate
	 * @param applydate  the value for tb_applicant.applyDate
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public void setApplydate(Date applydate) {
		this.applydate = applydate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_applicant.referrerName
	 * @return  the value of tb_applicant.referrerName
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public String getReferrername() {
		return referrername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_applicant.referrerName
	 * @param referrername  the value for tb_applicant.referrerName
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public void setReferrername(String referrername) {
		this.referrername = referrername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_applicant.creditCardNumber
	 * @return  the value of tb_applicant.creditCardNumber
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public String getCreditcardnumber() {
		return creditcardnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_applicant.creditCardNumber
	 * @param creditcardnumber  the value for tb_applicant.creditCardNumber
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public void setCreditcardnumber(String creditcardnumber) {
		this.creditcardnumber = creditcardnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_applicant.memberType
	 * @return  the value of tb_applicant.memberType
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public String getMembertype() {
		return membertype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_applicant.memberType
	 * @param membertype  the value for tb_applicant.memberType
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public void setMembertype(String membertype) {
		this.membertype = membertype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_applicant.CreatedDate
	 * @return  the value of tb_applicant.CreatedDate
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public Date getCreateddate() {
		return createddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_applicant.CreatedDate
	 * @param createddate  the value for tb_applicant.CreatedDate
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_applicant.ModifiedDate
	 * @return  the value of tb_applicant.ModifiedDate
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public Date getModifieddate() {
		return modifieddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_applicant.ModifiedDate
	 * @param modifieddate  the value for tb_applicant.ModifiedDate
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public void setModifieddate(Date modifieddate) {
		this.modifieddate = modifieddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_applicant.IsDeleted
	 * @return  the value of tb_applicant.IsDeleted
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public Boolean getIsdeleted() {
		return isdeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_applicant.IsDeleted
	 * @param isdeleted  the value for tb_applicant.IsDeleted
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public void setIsdeleted(Boolean isdeleted) {
		this.isdeleted = isdeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_applicant.status
	 * @return  the value of tb_applicant.status
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_applicant.status
	 * @param status  the value for tb_applicant.status
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_applicant.IsMember
	 * @return  the value of tb_applicant.IsMember
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public Boolean getIsmember() {
		return ismember;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_applicant.IsMember
	 * @param ismember  the value for tb_applicant.IsMember
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public void setIsmember(Boolean ismember) {
		this.ismember = ismember;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_applicant.IsReferrerTrue
	 * @return  the value of tb_applicant.IsReferrerTrue
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public Boolean getIsreferrertrue() {
		return isreferrertrue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_applicant.IsReferrerTrue
	 * @param isreferrertrue  the value for tb_applicant.IsReferrerTrue
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public void setIsreferrertrue(Boolean isreferrertrue) {
		this.isreferrertrue = isreferrertrue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_applicant.applicantEmail
	 * @return  the value of tb_applicant.applicantEmail
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public String getApplicantemail() {
		return applicantemail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_applicant.applicantEmail
	 * @param applicantemail  the value for tb_applicant.applicantEmail
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public void setApplicantemail(String applicantemail) {
		this.applicantemail = applicantemail;
	}
}