package com.dandelion.membership.dao.model;

import java.util.Date;

public class CalendarEvent {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_event.ID
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_event.title
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_event.cssClass
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	private String cssclass;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_event.start
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	private Date start;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_event.end
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	private Date end;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_event.url
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_event.CreatedDate
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	private Date createddate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_event.ModifiedDate
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	private Date modifieddate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_event.ID
	 * @return  the value of tb_event.ID
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_event.ID
	 * @param id  the value for tb_event.ID
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_event.title
	 * @return  the value of tb_event.title
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_event.title
	 * @param title  the value for tb_event.title
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_event.cssClass
	 * @return  the value of tb_event.cssClass
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public String getCssclass() {
		return cssclass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_event.cssClass
	 * @param cssclass  the value for tb_event.cssClass
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public void setCssclass(String cssclass) {
		this.cssclass = cssclass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_event.start
	 * @return  the value of tb_event.start
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public Date getStart() {
		return start;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_event.start
	 * @param start  the value for tb_event.start
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public void setStart(Date start) {
		this.start = start;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_event.end
	 * @return  the value of tb_event.end
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public Date getEnd() {
		return end;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_event.end
	 * @param end  the value for tb_event.end
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public void setEnd(Date end) {
		this.end = end;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_event.url
	 * @return  the value of tb_event.url
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_event.url
	 * @param url  the value for tb_event.url
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_event.CreatedDate
	 * @return  the value of tb_event.CreatedDate
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public Date getCreateddate() {
		return createddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_event.CreatedDate
	 * @param createddate  the value for tb_event.CreatedDate
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_event.ModifiedDate
	 * @return  the value of tb_event.ModifiedDate
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public Date getModifieddate() {
		return modifieddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_event.ModifiedDate
	 * @param modifieddate  the value for tb_event.ModifiedDate
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public void setModifieddate(Date modifieddate) {
		this.modifieddate = modifieddate;
	}
}