package com.dandelion.membership.dao.model;

import java.util.Date;

public class Field {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_field.ID
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_field.start
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	private Date start;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_field.end
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	private Date end;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_field.status
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_field.CreatedDate
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	private Date createddate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_field.ModifiedDate
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	private Date modifieddate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_field.ID
	 * @return  the value of tb_field.ID
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_field.ID
	 * @param id  the value for tb_field.ID
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_field.start
	 * @return  the value of tb_field.start
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public Date getStart() {
		return start;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_field.start
	 * @param start  the value for tb_field.start
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public void setStart(Date start) {
		this.start = start;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_field.end
	 * @return  the value of tb_field.end
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public Date getEnd() {
		return end;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_field.end
	 * @param end  the value for tb_field.end
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public void setEnd(Date end) {
		this.end = end;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_field.status
	 * @return  the value of tb_field.status
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_field.status
	 * @param status  the value for tb_field.status
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_field.CreatedDate
	 * @return  the value of tb_field.CreatedDate
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public Date getCreateddate() {
		return createddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_field.CreatedDate
	 * @param createddate  the value for tb_field.CreatedDate
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_field.ModifiedDate
	 * @return  the value of tb_field.ModifiedDate
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public Date getModifieddate() {
		return modifieddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_field.ModifiedDate
	 * @param modifieddate  the value for tb_field.ModifiedDate
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public void setModifieddate(Date modifieddate) {
		this.modifieddate = modifieddate;
	}
}