package com.dandelion.membership.dao.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ReservationExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tb_reservation
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tb_reservation
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tb_reservation
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_reservation
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public ReservationExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_reservation
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_reservation
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_reservation
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_reservation
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_reservation
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_reservation
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_reservation
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_reservation
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_reservation
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_reservation
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tb_reservation
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andMemberidfkIsNull() {
			addCriterion("memberIDFK is null");
			return (Criteria) this;
		}

		public Criteria andMemberidfkIsNotNull() {
			addCriterion("memberIDFK is not null");
			return (Criteria) this;
		}

		public Criteria andMemberidfkEqualTo(Long value) {
			addCriterion("memberIDFK =", value, "memberidfk");
			return (Criteria) this;
		}

		public Criteria andMemberidfkNotEqualTo(Long value) {
			addCriterion("memberIDFK <>", value, "memberidfk");
			return (Criteria) this;
		}

		public Criteria andMemberidfkGreaterThan(Long value) {
			addCriterion("memberIDFK >", value, "memberidfk");
			return (Criteria) this;
		}

		public Criteria andMemberidfkGreaterThanOrEqualTo(Long value) {
			addCriterion("memberIDFK >=", value, "memberidfk");
			return (Criteria) this;
		}

		public Criteria andMemberidfkLessThan(Long value) {
			addCriterion("memberIDFK <", value, "memberidfk");
			return (Criteria) this;
		}

		public Criteria andMemberidfkLessThanOrEqualTo(Long value) {
			addCriterion("memberIDFK <=", value, "memberidfk");
			return (Criteria) this;
		}

		public Criteria andMemberidfkIn(List<Long> values) {
			addCriterion("memberIDFK in", values, "memberidfk");
			return (Criteria) this;
		}

		public Criteria andMemberidfkNotIn(List<Long> values) {
			addCriterion("memberIDFK not in", values, "memberidfk");
			return (Criteria) this;
		}

		public Criteria andMemberidfkBetween(Long value1, Long value2) {
			addCriterion("memberIDFK between", value1, value2, "memberidfk");
			return (Criteria) this;
		}

		public Criteria andMemberidfkNotBetween(Long value1, Long value2) {
			addCriterion("memberIDFK not between", value1, value2, "memberidfk");
			return (Criteria) this;
		}

		public Criteria andFieldidfkIsNull() {
			addCriterion("fieldIDFK is null");
			return (Criteria) this;
		}

		public Criteria andFieldidfkIsNotNull() {
			addCriterion("fieldIDFK is not null");
			return (Criteria) this;
		}

		public Criteria andFieldidfkEqualTo(String value) {
			addCriterion("fieldIDFK =", value, "fieldidfk");
			return (Criteria) this;
		}

		public Criteria andFieldidfkNotEqualTo(String value) {
			addCriterion("fieldIDFK <>", value, "fieldidfk");
			return (Criteria) this;
		}

		public Criteria andFieldidfkGreaterThan(String value) {
			addCriterion("fieldIDFK >", value, "fieldidfk");
			return (Criteria) this;
		}

		public Criteria andFieldidfkGreaterThanOrEqualTo(String value) {
			addCriterion("fieldIDFK >=", value, "fieldidfk");
			return (Criteria) this;
		}

		public Criteria andFieldidfkLessThan(String value) {
			addCriterion("fieldIDFK <", value, "fieldidfk");
			return (Criteria) this;
		}

		public Criteria andFieldidfkLessThanOrEqualTo(String value) {
			addCriterion("fieldIDFK <=", value, "fieldidfk");
			return (Criteria) this;
		}

		public Criteria andFieldidfkLike(String value) {
			addCriterion("fieldIDFK like", value, "fieldidfk");
			return (Criteria) this;
		}

		public Criteria andFieldidfkNotLike(String value) {
			addCriterion("fieldIDFK not like", value, "fieldidfk");
			return (Criteria) this;
		}

		public Criteria andFieldidfkIn(List<String> values) {
			addCriterion("fieldIDFK in", values, "fieldidfk");
			return (Criteria) this;
		}

		public Criteria andFieldidfkNotIn(List<String> values) {
			addCriterion("fieldIDFK not in", values, "fieldidfk");
			return (Criteria) this;
		}

		public Criteria andFieldidfkBetween(String value1, String value2) {
			addCriterion("fieldIDFK between", value1, value2, "fieldidfk");
			return (Criteria) this;
		}

		public Criteria andFieldidfkNotBetween(String value1, String value2) {
			addCriterion("fieldIDFK not between", value1, value2, "fieldidfk");
			return (Criteria) this;
		}

		public Criteria andStartIsNull() {
			addCriterion("start is null");
			return (Criteria) this;
		}

		public Criteria andStartIsNotNull() {
			addCriterion("start is not null");
			return (Criteria) this;
		}

		public Criteria andStartEqualTo(Date value) {
			addCriterion("start =", value, "start");
			return (Criteria) this;
		}

		public Criteria andStartNotEqualTo(Date value) {
			addCriterion("start <>", value, "start");
			return (Criteria) this;
		}

		public Criteria andStartGreaterThan(Date value) {
			addCriterion("start >", value, "start");
			return (Criteria) this;
		}

		public Criteria andStartGreaterThanOrEqualTo(Date value) {
			addCriterion("start >=", value, "start");
			return (Criteria) this;
		}

		public Criteria andStartLessThan(Date value) {
			addCriterion("start <", value, "start");
			return (Criteria) this;
		}

		public Criteria andStartLessThanOrEqualTo(Date value) {
			addCriterion("start <=", value, "start");
			return (Criteria) this;
		}

		public Criteria andStartIn(List<Date> values) {
			addCriterion("start in", values, "start");
			return (Criteria) this;
		}

		public Criteria andStartNotIn(List<Date> values) {
			addCriterion("start not in", values, "start");
			return (Criteria) this;
		}

		public Criteria andStartBetween(Date value1, Date value2) {
			addCriterion("start between", value1, value2, "start");
			return (Criteria) this;
		}

		public Criteria andStartNotBetween(Date value1, Date value2) {
			addCriterion("start not between", value1, value2, "start");
			return (Criteria) this;
		}

		public Criteria andEndIsNull() {
			addCriterion("end is null");
			return (Criteria) this;
		}

		public Criteria andEndIsNotNull() {
			addCriterion("end is not null");
			return (Criteria) this;
		}

		public Criteria andEndEqualTo(Date value) {
			addCriterion("end =", value, "end");
			return (Criteria) this;
		}

		public Criteria andEndNotEqualTo(Date value) {
			addCriterion("end <>", value, "end");
			return (Criteria) this;
		}

		public Criteria andEndGreaterThan(Date value) {
			addCriterion("end >", value, "end");
			return (Criteria) this;
		}

		public Criteria andEndGreaterThanOrEqualTo(Date value) {
			addCriterion("end >=", value, "end");
			return (Criteria) this;
		}

		public Criteria andEndLessThan(Date value) {
			addCriterion("end <", value, "end");
			return (Criteria) this;
		}

		public Criteria andEndLessThanOrEqualTo(Date value) {
			addCriterion("end <=", value, "end");
			return (Criteria) this;
		}

		public Criteria andEndIn(List<Date> values) {
			addCriterion("end in", values, "end");
			return (Criteria) this;
		}

		public Criteria andEndNotIn(List<Date> values) {
			addCriterion("end not in", values, "end");
			return (Criteria) this;
		}

		public Criteria andEndBetween(Date value1, Date value2) {
			addCriterion("end between", value1, value2, "end");
			return (Criteria) this;
		}

		public Criteria andEndNotBetween(Date value1, Date value2) {
			addCriterion("end not between", value1, value2, "end");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("status like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("status not like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<String> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<String> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(String value1, String value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andWeatherIsNull() {
			addCriterion("weather is null");
			return (Criteria) this;
		}

		public Criteria andWeatherIsNotNull() {
			addCriterion("weather is not null");
			return (Criteria) this;
		}

		public Criteria andWeatherEqualTo(String value) {
			addCriterion("weather =", value, "weather");
			return (Criteria) this;
		}

		public Criteria andWeatherNotEqualTo(String value) {
			addCriterion("weather <>", value, "weather");
			return (Criteria) this;
		}

		public Criteria andWeatherGreaterThan(String value) {
			addCriterion("weather >", value, "weather");
			return (Criteria) this;
		}

		public Criteria andWeatherGreaterThanOrEqualTo(String value) {
			addCriterion("weather >=", value, "weather");
			return (Criteria) this;
		}

		public Criteria andWeatherLessThan(String value) {
			addCriterion("weather <", value, "weather");
			return (Criteria) this;
		}

		public Criteria andWeatherLessThanOrEqualTo(String value) {
			addCriterion("weather <=", value, "weather");
			return (Criteria) this;
		}

		public Criteria andWeatherLike(String value) {
			addCriterion("weather like", value, "weather");
			return (Criteria) this;
		}

		public Criteria andWeatherNotLike(String value) {
			addCriterion("weather not like", value, "weather");
			return (Criteria) this;
		}

		public Criteria andWeatherIn(List<String> values) {
			addCriterion("weather in", values, "weather");
			return (Criteria) this;
		}

		public Criteria andWeatherNotIn(List<String> values) {
			addCriterion("weather not in", values, "weather");
			return (Criteria) this;
		}

		public Criteria andWeatherBetween(String value1, String value2) {
			addCriterion("weather between", value1, value2, "weather");
			return (Criteria) this;
		}

		public Criteria andWeatherNotBetween(String value1, String value2) {
			addCriterion("weather not between", value1, value2, "weather");
			return (Criteria) this;
		}

		public Criteria andEventIsNull() {
			addCriterion("event is null");
			return (Criteria) this;
		}

		public Criteria andEventIsNotNull() {
			addCriterion("event is not null");
			return (Criteria) this;
		}

		public Criteria andEventEqualTo(String value) {
			addCriterion("event =", value, "event");
			return (Criteria) this;
		}

		public Criteria andEventNotEqualTo(String value) {
			addCriterion("event <>", value, "event");
			return (Criteria) this;
		}

		public Criteria andEventGreaterThan(String value) {
			addCriterion("event >", value, "event");
			return (Criteria) this;
		}

		public Criteria andEventGreaterThanOrEqualTo(String value) {
			addCriterion("event >=", value, "event");
			return (Criteria) this;
		}

		public Criteria andEventLessThan(String value) {
			addCriterion("event <", value, "event");
			return (Criteria) this;
		}

		public Criteria andEventLessThanOrEqualTo(String value) {
			addCriterion("event <=", value, "event");
			return (Criteria) this;
		}

		public Criteria andEventLike(String value) {
			addCriterion("event like", value, "event");
			return (Criteria) this;
		}

		public Criteria andEventNotLike(String value) {
			addCriterion("event not like", value, "event");
			return (Criteria) this;
		}

		public Criteria andEventIn(List<String> values) {
			addCriterion("event in", values, "event");
			return (Criteria) this;
		}

		public Criteria andEventNotIn(List<String> values) {
			addCriterion("event not in", values, "event");
			return (Criteria) this;
		}

		public Criteria andEventBetween(String value1, String value2) {
			addCriterion("event between", value1, value2, "event");
			return (Criteria) this;
		}

		public Criteria andEventNotBetween(String value1, String value2) {
			addCriterion("event not between", value1, value2, "event");
			return (Criteria) this;
		}

		public Criteria andCreateddateIsNull() {
			addCriterion("CreatedDate is null");
			return (Criteria) this;
		}

		public Criteria andCreateddateIsNotNull() {
			addCriterion("CreatedDate is not null");
			return (Criteria) this;
		}

		public Criteria andCreateddateEqualTo(Date value) {
			addCriterion("CreatedDate =", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateNotEqualTo(Date value) {
			addCriterion("CreatedDate <>", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateGreaterThan(Date value) {
			addCriterion("CreatedDate >", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateGreaterThanOrEqualTo(Date value) {
			addCriterion("CreatedDate >=", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateLessThan(Date value) {
			addCriterion("CreatedDate <", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateLessThanOrEqualTo(Date value) {
			addCriterion("CreatedDate <=", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateIn(List<Date> values) {
			addCriterion("CreatedDate in", values, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateNotIn(List<Date> values) {
			addCriterion("CreatedDate not in", values, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateBetween(Date value1, Date value2) {
			addCriterion("CreatedDate between", value1, value2, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateNotBetween(Date value1, Date value2) {
			addCriterion("CreatedDate not between", value1, value2,
					"createddate");
			return (Criteria) this;
		}

		public Criteria andModifieddateIsNull() {
			addCriterion("ModifiedDate is null");
			return (Criteria) this;
		}

		public Criteria andModifieddateIsNotNull() {
			addCriterion("ModifiedDate is not null");
			return (Criteria) this;
		}

		public Criteria andModifieddateEqualTo(Date value) {
			addCriterion("ModifiedDate =", value, "modifieddate");
			return (Criteria) this;
		}

		public Criteria andModifieddateNotEqualTo(Date value) {
			addCriterion("ModifiedDate <>", value, "modifieddate");
			return (Criteria) this;
		}

		public Criteria andModifieddateGreaterThan(Date value) {
			addCriterion("ModifiedDate >", value, "modifieddate");
			return (Criteria) this;
		}

		public Criteria andModifieddateGreaterThanOrEqualTo(Date value) {
			addCriterion("ModifiedDate >=", value, "modifieddate");
			return (Criteria) this;
		}

		public Criteria andModifieddateLessThan(Date value) {
			addCriterion("ModifiedDate <", value, "modifieddate");
			return (Criteria) this;
		}

		public Criteria andModifieddateLessThanOrEqualTo(Date value) {
			addCriterion("ModifiedDate <=", value, "modifieddate");
			return (Criteria) this;
		}

		public Criteria andModifieddateIn(List<Date> values) {
			addCriterion("ModifiedDate in", values, "modifieddate");
			return (Criteria) this;
		}

		public Criteria andModifieddateNotIn(List<Date> values) {
			addCriterion("ModifiedDate not in", values, "modifieddate");
			return (Criteria) this;
		}

		public Criteria andModifieddateBetween(Date value1, Date value2) {
			addCriterion("ModifiedDate between", value1, value2, "modifieddate");
			return (Criteria) this;
		}

		public Criteria andModifieddateNotBetween(Date value1, Date value2) {
			addCriterion("ModifiedDate not between", value1, value2,
					"modifieddate");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tb_reservation
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_reservation
     *
     * @mbggenerated do_not_delete_during_merge Mon Nov 18 15:00:22 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}