package com.dandelion.membership.dao.data;

import com.dandelion.membership.dao.model.CalendarEvent;
import com.dandelion.membership.dao.model.CalendarEventExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CalendarEventMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_event
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	int countByExample(CalendarEventExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_event
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	int deleteByExample(CalendarEventExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_event
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_event
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	int insert(CalendarEvent record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_event
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	int insertSelective(CalendarEvent record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_event
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	List<CalendarEvent> selectByExample(CalendarEventExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_event
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	CalendarEvent selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_event
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	int updateByExampleSelective(@Param("record") CalendarEvent record,
			@Param("example") CalendarEventExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_event
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	int updateByExample(@Param("record") CalendarEvent record,
			@Param("example") CalendarEventExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_event
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	int updateByPrimaryKeySelective(CalendarEvent record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_event
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	int updateByPrimaryKey(CalendarEvent record);
}