package com.dandelion.membership.dao.data;

import com.dandelion.membership.dao.model.Field;
import com.dandelion.membership.dao.model.FieldExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FieldMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_field
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	int countByExample(FieldExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_field
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	int deleteByExample(FieldExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_field
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_field
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	int insert(Field record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_field
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	int insertSelective(Field record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_field
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	List<Field> selectByExample(FieldExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_field
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	Field selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_field
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	int updateByExampleSelective(@Param("record") Field record,
			@Param("example") FieldExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_field
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	int updateByExample(@Param("record") Field record,
			@Param("example") FieldExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_field
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	int updateByPrimaryKeySelective(Field record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_field
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	int updateByPrimaryKey(Field record);
}