package com.dandelion.membership.dao.data;

import com.dandelion.membership.dao.model.Reservation;
import com.dandelion.membership.dao.model.ReservationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReservationMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_reservation
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	int countByExample(ReservationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_reservation
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	int deleteByExample(ReservationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_reservation
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_reservation
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	int insert(Reservation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_reservation
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	int insertSelective(Reservation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_reservation
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	List<Reservation> selectByExample(ReservationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_reservation
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	Reservation selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_reservation
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	int updateByExampleSelective(@Param("record") Reservation record,
			@Param("example") ReservationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_reservation
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	int updateByExample(@Param("record") Reservation record,
			@Param("example") ReservationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_reservation
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	int updateByPrimaryKeySelective(Reservation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_reservation
	 * @mbggenerated  Mon Nov 18 21:45:04 CST 2013
	 */
	int updateByPrimaryKey(Reservation record);
}